name: Auto Merge to Develop

on:
  push:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge main into develop
        run: |
          git checkout develop
          if ! git merge main; then
            echo "Error: Merge conflict detected"
            exit 1
          fi
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Reset to nearest commit of develop and checkout to main
        if: failure()
        run: |
          git reset --hard origin/develop
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a pull request if fail
        if: failure()
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge main into develop"
          title: "Merge main into develop"
          body: "Auto-merge failed. Please resolve the conflict and merge main into develop."
          branch: auto-pr/main-to-developer
          base: develop
          labels: auto-merge
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
