name: Auto Merge to Develop

on:
  push:
    branches:
      - main

env:
  DEVELOP_BRANCH: develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # - name: Return error
      #   run: |
      #     echo "Error: Merge conflict detected"
      #     exit 1

      - name: Merge main into develop
        run: |
          git checkout $DEVELOP_BRANCH
          if ! git merge main --no-edit; then
            echo "Error: Merge conflict detected"
            exit 1
          fi
          git push origin $DEVELOP_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Reset to nearest commit of develop and checkout to main
        if: failure()
        run: |
          git reset --hard origin/$DEVELOP_BRANCH
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a pull request if fail
        if: failure()
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge main into develop"
          title: "Merge main into develop"
          body-path: .github/PULL_REQUEST_TEMPLATE.md
          branch: ${{ github.ref }}
          base: ${{ env.DEVELOP_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
